// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJjOztjHoLogL9WA54E8QXAgNJItFl5DY',
    appId: '1:445183691218:web:49a8adfc3569cdecf0600b',
    messagingSenderId: '445183691218',
    projectId: 'authenticationapp-2f932',
    authDomain: 'authenticationapp-2f932.firebaseapp.com',
    storageBucket: 'authenticationapp-2f932.appspot.com',
    measurementId: 'G-V0R565TDWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS7akf_UIbpG6uq0xhQokEDEFkY_iw864',
    appId: '1:445183691218:android:3423aaecc945d4c5f0600b',
    messagingSenderId: '445183691218',
    projectId: 'authenticationapp-2f932',
    storageBucket: 'authenticationapp-2f932.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_-8ZaJ2OgECLjcjHl0mpESThnn83wMwI',
    appId: '1:445183691218:ios:a4bfb77c7edbd0f2f0600b',
    messagingSenderId: '445183691218',
    projectId: 'authenticationapp-2f932',
    storageBucket: 'authenticationapp-2f932.appspot.com',
    iosBundleId: 'com.example.ibitfApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_-8ZaJ2OgECLjcjHl0mpESThnn83wMwI',
    appId: '1:445183691218:ios:a4bfb77c7edbd0f2f0600b',
    messagingSenderId: '445183691218',
    projectId: 'authenticationapp-2f932',
    storageBucket: 'authenticationapp-2f932.appspot.com',
    iosBundleId: 'com.example.ibitfApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJjOztjHoLogL9WA54E8QXAgNJItFl5DY',
    appId: '1:445183691218:web:0fd8339779842d00f0600b',
    messagingSenderId: '445183691218',
    projectId: 'authenticationapp-2f932',
    authDomain: 'authenticationapp-2f932.firebaseapp.com',
    storageBucket: 'authenticationapp-2f932.appspot.com',
    measurementId: 'G-0HPX1ZRYT3',
  );

}